version: "3"

services:
    # https://hub.docker.com/_/rabbitmq
    rabbit:
        image: rabbitmq:3.8-alpine
        container_name: forumodua-parser-rebbit
        env_file: .env
        networks:
        - forumodua-network

    # https://hub.docker.com/_/postgres
    postgres:
        image: postgres:12.2-alpine
        container_name: forumodua-parser-postgresql
        env_file: .env
        ports:
        - 5432:5432
        volumes:
        - ./migrations:/docker-entrypoint-initdb.d
        networks:
        - forumodua-network

    # https://hub.docker.com/_/php
    php:
        build:
            context: ./
            dockerfile: Dockerfile
        container_name: forumodua-parser-php
        env_file: .env
        depends_on:
        - postgres
        - rabbit
        command: php bin/consumer
        networks:
        - forumodua-network
        volumes:
        - .:/usr/src/app

networks:
    forumodua-network: {}