#!/usr/bin/env bash

#docker run --rm --interactive --tty --network=forumodua-network --env-file $PWD/.env --volume $PWD:/usr/src/app forumodua-parser_php bin/parser "$@"
docker-compose exec php bin/parser "$@"
